/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Link;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkRecord extends UpdatableRecordImpl<LinkRecord> implements Record7<Long, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINK.ID</code>.
     */
    public void setId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINK.ID</code>.
     */
    @NotNull
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LINK.URL</code>.
     */
    public void setUrl(@NotNull String value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINK.URL</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 255)
    @NotNull
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>LINK.UPDATED_AT</code>.
     */
    public void setUpdatedAt(@NotNull LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>LINK.UPDATED_AT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>LINK.LAST_CHECK_AT</code>.
     */
    public void setLastCheckAt(@NotNull LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>LINK.LAST_CHECK_AT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public LocalDateTime getLastCheckAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>LINK.LAST_COMMIT_AT</code>.
     */
    public void setLastCommitAt(@Nullable LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>LINK.LAST_COMMIT_AT</code>.
     */
    @Nullable
    public LocalDateTime getLastCommitAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>LINK.ISSUES_COUNT</code>.
     */
    public void setIssuesCount(@Nullable Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>LINK.ISSUES_COUNT</code>.
     */
    @Nullable
    public Integer getIssuesCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>LINK.ANSWER_COUNT</code>.
     */
    public void setAnswerCount(@Nullable Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>LINK.ANSWER_COUNT</code>.
     */
    @Nullable
    public Integer getAnswerCount() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row7<Long, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row7<Long, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Link.LINK.ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return Link.LINK.URL;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field3() {
        return Link.LINK.UPDATED_AT;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field4() {
        return Link.LINK.LAST_CHECK_AT;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field5() {
        return Link.LINK.LAST_COMMIT_AT;
    }

    @Override
    @NotNull
    public Field<Integer> field6() {
        return Link.LINK.ISSUES_COUNT;
    }

    @Override
    @NotNull
    public Field<Integer> field7() {
        return Link.LINK.ANSWER_COUNT;
    }

    @Override
    @NotNull
    public Long component1() {
        return getId();
    }

    @Override
    @NotNull
    public String component2() {
        return getUrl();
    }

    @Override
    @NotNull
    public LocalDateTime component3() {
        return getUpdatedAt();
    }

    @Override
    @NotNull
    public LocalDateTime component4() {
        return getLastCheckAt();
    }

    @Override
    @Nullable
    public LocalDateTime component5() {
        return getLastCommitAt();
    }

    @Override
    @Nullable
    public Integer component6() {
        return getIssuesCount();
    }

    @Override
    @Nullable
    public Integer component7() {
        return getAnswerCount();
    }

    @Override
    @NotNull
    public Long value1() {
        return getId();
    }

    @Override
    @NotNull
    public String value2() {
        return getUrl();
    }

    @Override
    @NotNull
    public LocalDateTime value3() {
        return getUpdatedAt();
    }

    @Override
    @NotNull
    public LocalDateTime value4() {
        return getLastCheckAt();
    }

    @Override
    @Nullable
    public LocalDateTime value5() {
        return getLastCommitAt();
    }

    @Override
    @Nullable
    public Integer value6() {
        return getIssuesCount();
    }

    @Override
    @Nullable
    public Integer value7() {
        return getAnswerCount();
    }

    @Override
    @NotNull
    public LinkRecord value1(@NotNull Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value2(@NotNull String value) {
        setUrl(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value3(@NotNull LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value4(@NotNull LocalDateTime value) {
        setLastCheckAt(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value5(@Nullable LocalDateTime value) {
        setLastCommitAt(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value6(@Nullable Integer value) {
        setIssuesCount(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value7(@Nullable Integer value) {
        setAnswerCount(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord values(@NotNull Long value1, @NotNull String value2, @NotNull LocalDateTime value3, @NotNull LocalDateTime value4, @Nullable LocalDateTime value5, @Nullable Integer value6, @Nullable Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkRecord
     */
    public LinkRecord() {
        super(Link.LINK);
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    @ConstructorProperties({ "id", "url", "updatedAt", "lastCheckAt", "lastCommitAt", "issuesCount", "answerCount" })
    public LinkRecord(@NotNull Long id, @NotNull String url, @NotNull LocalDateTime updatedAt, @NotNull LocalDateTime lastCheckAt, @Nullable LocalDateTime lastCommitAt, @Nullable Integer issuesCount, @Nullable Integer answerCount) {
        super(Link.LINK);

        setId(id);
        setUrl(url);
        setUpdatedAt(updatedAt);
        setLastCheckAt(lastCheckAt);
        setLastCommitAt(lastCommitAt);
        setIssuesCount(issuesCount);
        setAnswerCount(answerCount);
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    public LinkRecord(ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos.Link value) {
        super(Link.LINK);

        if (value != null) {
            setId(value.getId());
            setUrl(value.getUrl());
            setUpdatedAt(value.getUpdatedAt());
            setLastCheckAt(value.getLastCheckAt());
            setLastCommitAt(value.getLastCommitAt());
            setIssuesCount(value.getIssuesCount());
            setAnswerCount(value.getAnswerCount());
        }
    }
}
