app:
  test: 1
  scheduler:
    interval: 15000
    check_delay_minutes: 10
  bot:
    url: http://localhost:8081
  database-access-type: jpa
  use-queue: true
  rabbitmq:
    exchange-name: link-exchange
    queue-name: link-queue

springdoc:
  swagger-ui:
    path: swagger-ui

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

management:
  server:
    port: 8082
  endpoints:
    web:
      base-path: /
      exposure:
        include: "info,health,prometheus"
      path-mapping:
        prometheus: metrics
  metrics:
    tags:
      application: ${spring.application.name}
