/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Link implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String url;
    private LocalDateTime updatedAt;
    private LocalDateTime lastCheckAt;
    private LocalDateTime lastCommitAt;
    private Integer issuesCount;
    private Integer answerCount;

    public Link() {}

    public Link(Link value) {
        this.id = value.id;
        this.url = value.url;
        this.updatedAt = value.updatedAt;
        this.lastCheckAt = value.lastCheckAt;
        this.lastCommitAt = value.lastCommitAt;
        this.issuesCount = value.issuesCount;
        this.answerCount = value.answerCount;
    }

    @ConstructorProperties({ "id", "url", "updatedAt", "lastCheckAt", "lastCommitAt", "issuesCount", "answerCount" })
    public Link(
        @NotNull Long id,
        @NotNull String url,
        @NotNull LocalDateTime updatedAt,
        @NotNull LocalDateTime lastCheckAt,
        @Nullable LocalDateTime lastCommitAt,
        @Nullable Integer issuesCount,
        @Nullable Integer answerCount
    ) {
        this.id = id;
        this.url = url;
        this.updatedAt = updatedAt;
        this.lastCheckAt = lastCheckAt;
        this.lastCommitAt = lastCommitAt;
        this.issuesCount = issuesCount;
        this.answerCount = answerCount;
    }

    /**
     * Getter for <code>LINK.ID</code>.
     */
    @NotNull
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>LINK.ID</code>.
     */
    public void setId(@NotNull Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>LINK.URL</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 255)
    @NotNull
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>LINK.URL</code>.
     */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

    /**
     * Getter for <code>LINK.UPDATED_AT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>LINK.UPDATED_AT</code>.
     */
    public void setUpdatedAt(@NotNull LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>LINK.LAST_CHECK_AT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public LocalDateTime getLastCheckAt() {
        return this.lastCheckAt;
    }

    /**
     * Setter for <code>LINK.LAST_CHECK_AT</code>.
     */
    public void setLastCheckAt(@NotNull LocalDateTime lastCheckAt) {
        this.lastCheckAt = lastCheckAt;
    }

    /**
     * Getter for <code>LINK.LAST_COMMIT_AT</code>.
     */
    @Nullable
    public LocalDateTime getLastCommitAt() {
        return this.lastCommitAt;
    }

    /**
     * Setter for <code>LINK.LAST_COMMIT_AT</code>.
     */
    public void setLastCommitAt(@Nullable LocalDateTime lastCommitAt) {
        this.lastCommitAt = lastCommitAt;
    }

    /**
     * Getter for <code>LINK.ISSUES_COUNT</code>.
     */
    @Nullable
    public Integer getIssuesCount() {
        return this.issuesCount;
    }

    /**
     * Setter for <code>LINK.ISSUES_COUNT</code>.
     */
    public void setIssuesCount(@Nullable Integer issuesCount) {
        this.issuesCount = issuesCount;
    }

    /**
     * Getter for <code>LINK.ANSWER_COUNT</code>.
     */
    @Nullable
    public Integer getAnswerCount() {
        return this.answerCount;
    }

    /**
     * Setter for <code>LINK.ANSWER_COUNT</code>.
     */
    public void setAnswerCount(@Nullable Integer answerCount) {
        this.answerCount = answerCount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Link other = (Link) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.url == null) {
            if (other.url != null)
                return false;
        }
        else if (!this.url.equals(other.url))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        if (this.lastCheckAt == null) {
            if (other.lastCheckAt != null)
                return false;
        }
        else if (!this.lastCheckAt.equals(other.lastCheckAt))
            return false;
        if (this.lastCommitAt == null) {
            if (other.lastCommitAt != null)
                return false;
        }
        else if (!this.lastCommitAt.equals(other.lastCommitAt))
            return false;
        if (this.issuesCount == null) {
            if (other.issuesCount != null)
                return false;
        }
        else if (!this.issuesCount.equals(other.issuesCount))
            return false;
        if (this.answerCount == null) {
            if (other.answerCount != null)
                return false;
        }
        else if (!this.answerCount.equals(other.answerCount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.lastCheckAt == null) ? 0 : this.lastCheckAt.hashCode());
        result = prime * result + ((this.lastCommitAt == null) ? 0 : this.lastCommitAt.hashCode());
        result = prime * result + ((this.issuesCount == null) ? 0 : this.issuesCount.hashCode());
        result = prime * result + ((this.answerCount == null) ? 0 : this.answerCount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Link (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(lastCheckAt);
        sb.append(", ").append(lastCommitAt);
        sb.append(", ").append(issuesCount);
        sb.append(", ").append(answerCount);

        sb.append(")");
        return sb.toString();
    }
}
