app:
  test: 1
  bot:
    token: ${BOT_TOKEN}
    name: link_tracking_bot
  scrapper:
    url: http://localhost:8080
  rabbitmq:
    exchange-name: link-exchange
    queue-name: link-queue

springdoc:
  swagger-ui:
    path: swagger-ui

server:
  port: 8081

spring:
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false